piadas_p = [
    "Por que o lápis ficou com depressão? Porque estava sem ponta!",
    "Qual é o café mais perigoso do mundo? O ex-presso!",
    "Por que o livro foi ao médico? Porque estava se sentindo meio 'lido' demais.",
    "O que o zero disse para o oito? Belo cinto!",
    "Por que a matemática é triste? Porque tem muitos problemas.",
    "O que o tomate foi fazer no banco? Tirar extrato.",
    "Por que a vaca foi para o espaço? Para ver a Via Láctea.",
    "Como o pão se comunica? Pelo Wi-fi!",
    "Por que o relógio foi preso? Porque ele matou o tempo.",
    "O que acontece quando chove na França? Vira 'França molhada'.",
    "Qual é o animal mais antigo do mundo? A zebra — porque é toda em preto e branco.",
    "Por que o computador foi ao médico? Porque estava com um vírus.",
    "Como se chama um boi com três pernas? Tri-pé.",
    "Por que o cachorro entrou na igreja? Porque era um cão-fiel.",
    "O que o cadeado disse para a chave? Você me abre!",
    "Por que o fotógrafo foi preso? Porque ele foi 'revelado'.",
    "Qual é o cúmulo do azulejo? Ter uma vida toda 'em quadrado'.",
    "Por que o fósforo se suic… deixa pra lá, ele só apagou mesmo.",
    "Por que o astronauta não usa computador? Porque ele tem medo de 'vazar dados'.",
    "Qual é o contrário de volátil? Vem cá sobrinho!",
    "Por que o computador foi ao médico? Porque pegou um vírus.",
    "O que o tomate disse para o outro tomate no trânsito? Ketchup!",
    "Por que o lápis se sentiu mal? Porque estava sem ponta.",
    "Qual é o cúmulo do egoísmo? Guardar a piada só para si.",
    "Por que o pão foi ao psicólogo? Porque se sentia amassado.",
    "O que o zero disse para o oito? Belo cinto!",
    "Por que o livro de matemática estava triste? Porque tinha muitos problemas.",
    "Por que a galinha atravessou o parque de diversões? Para ir ao outro lado do carrossel.",
    "O que a abelha disse para o mel? Sem você, eu não sou nada.",
    "Por que a bicicleta caiu? Porque estava de duas-tiada.",
    "Por que o café foi preso? Porque bateu no leite.",
    "Qual é o cúmulo da paciência? Esperar a geladeira descongelar sozinha.",
    "O que o boi disse para a vaca? Te amoOOooo!",
    "Por que o relógio foi ao psicólogo? Estava sem tempo.",
    "O que o elevador disse para o prédio? Estou subindo!",
    "Por que o milho virou pipoca? Porque entrou em pressão.",
    "Por que o rato foi à aula de informática? Para aprender a clicar.",
    "O que o rádio disse para a antena? Estamos sintonizados!",
    "Por que o pão não briga? Porque ele é massa pacífica.",
    "Qual o cúmulo da alegria? Rir de uma piada que ainda não acabou.",
    "Por que a escada foi ao médico? Estava cansada de subir.",
    "Por que o gato gosta de sentar no teclado? Porque quer digitar miau.",
    "Por que o computador não briga? Porque prefere ficar offline.",
    "O que a caneta disse para o papel? Você completa meu traço.",
    "Por que o poste não luta? Porque é iluminado.",
    "O que a nuvem disse para o vento? Não me leve a mal.",
    "Por que o gelo não vai à escola? Porque derrete com a pressão.",
    "Por que o livro nunca mente? Porque tem capa dura.",
    "O que o sapato disse para o pé? Para de pisar em mim!",
    "Por que o tomate ficou vermelho? Porque viu a salada.",
    "Por que o sorvete não fala? Porque é frio demais.",
    "O que o fantasma disse para o outro? Booa noite!",
    "Por que a porta não abre? Porque está fechada.",
    "Qual é o cúmulo da limpeza? Lavar a água.",
    "O que o fogo disse para a vela? Não derreta por mim.",
    "Por que o vento é bagunceiro? Porque vive soprando.",
    "Por que o chocolate se derrete? Porque está apaixonado.",
    "O que a cadeira disse para a mesa? Tamo junto no jantar.",
    "Por que o avião não briga? Porque voa longe do problema.",
    "Por que o pão ficou famoso? Porque é massa!",
    "Por que a nuvem chove? Porque não aguenta mais guardar.",
    "Por que o rádio não corre? Porque sempre sintoniza.",
    "Por que a banana vai ao médico? Para tirar casca.",
    "O que o cabo disse para a tomada? Ligados para sempre.",
    "Por que o cavalo não vai ao cinema? Porque já viu o trailer.",
    "Por que o livro não sai de casa? Porque tem capa.",
    "Por que o poste não dorme? Porque fica aceso.",
    "Por que o peixe não vai para a escola? Porque está na rede.",
    "Por que a colher não entra na briga? Porque só mexe.",
    "Por que a bola foi presa? Porque estava quicando.",
    "O que a lâmpada disse? Estou brilhando hoje.",
    "Por que o relógio é pontual? Porque tem hora marcada.",
    "Por que o fio não fala? Porque é elétrico.",
    "Por que o rato não fala? Porque é mudo.",
    "Por que a chuva cai? Porque não sabe subir.",
    "Por que o computador adora praia? Porque gosta de surfear na web.",
    "Por que o peixe não gosta de escola? Porque não quer virar peixe-escola.",
    "Qual é o cúmulo da velocidade? Fechar os olhos e abrir sem ver nada.",
    "O que o espelho disse para o pente? Me ajuda a me manter apresentável.",
    "Por que o trigo nunca briga? Porque é sempre farinha do mesmo saco.",
    "Por que o macaco gosta de banana? Porque dá vitamina.",
    "Por que a galinha não joga futebol? Porque ela vive perdendo a cabeça.",
    "O que o pão disse para a manteiga? Você me derrete.",
    "Por que o sorvete nunca mente? Porque derrete a verdade.",
    "Por que o gato usa óculos? Porque miauuu-visão.",
    "Por que o chocolate nunca briga? Porque sempre se derrete de rir.",
    "O que o lápis falou para o apontador? Para de roer minhas ideias!",
    "Por que a impressora é ruim de memória? Porque sempre imprime o mesmo.",
    "Por que o fantasma não gosta de festa? Porque se sente invisível.",
    "O que a árvore disse para o vento? Me deixa em paz!",
    "Por que o pão dorme cedo? Porque está esgotado.",
    "Qual é o cúmulo da alegria? Rir sozinho no elevador.",
    "O que a abelha disse para a flor? Você me deixa meloso.",
    "Por que a água não gosta de segredo? Porque escorre tudo.",
    "O que o jacaré disse para o amigo? Croc, croc, estou aqui!",
    "Por que o boi se esconde? Porque é manso demais.",
    "Por que a galinha canta de manhã? Para acordar o vizinho.",
    "O que a lua disse para o sol? Você me ofusca.",
    "Por que o poste é bom conselheiro? Porque ilumina os caminhos.",
    "Por que o ovo não conta piadas? Porque quebra a casca de rir.",
    "Por que o caminhão é forte? Porque carrega o mundo.",
    "O que a lâmpada disse ao interruptor? Acenda-me por favor.",
    "Por que o pombo não usa WhatsApp? Porque já tem pombo correio.",
    "Qual é o cúmulo do frio? Tomar banho de neve sem se molhar.",
    "Por que o sorvete não fala nada? Porque está gelado.",
    "O que o pneu disse para o carro? Estou ligado em você.",
    "Por que a banana é engraçada? Porque dá muita risada-fruta.",
    "Por que o celular não briga? Porque prefere ficar no modo silencioso.",
    "O que o boi falou para a vaca? Te amoOOooo!",
    "Por que o computador foi preso? Porque bateu no mouse.",
    "Por que o lápis nunca se perde? Porque sempre deixa um traço.",
    "O que o fogo disse para a vela? Não derreta por mim.",
    "Por que o macaco não gosta de matemática? Porque vive fazendo contas de cabeça.",
    "Por que o rádio vive feliz? Porque sempre está na estação certa.",
    "Qual é o cúmulo da força? Levantar a própria sombra.",
    "O que o vento disse para o cabelo? Me deixa bagunçado.",
    "Por que a bicicleta não corre? Porque está sempre pedalando devagar.",
    "O que o queijo disse para o pão? Você me completa.",
    "Por que a porta não gosta de festa? Porque sempre fica de fora.",
    "Por que o milho virou pipoca? Porque explodiu de alegria.",
    "Por que o sorvete foi ao médico? Porque estava se sentindo derretido.",
    "O que o lápis disse para o papel? Sem você, não tenho sentido.",
    "Por que o computador adora praia? Porque gosta de surfar na web.",
    "O que o pão falou para a manteiga? Você me deixa mais leve.",
    "Por que o cavalo não usa celular? Porque ele prefere trote a mensagens.",
    "O que a caneta disse para o caderno? Você é meu par perfeito.",
    "Por que o relógio foi ao psicólogo? Porque estava sem tempo.",
    "Por que a cadeira sempre ganha no jogo? Porque sempre está sentada no trono.",
    "O que o rádio disse para o CD? Você é antigo, mas legal.",
    "Por que o gato usa computador? Porque quer caçar o mouse.",
    "Por que o chocolate gosta de abraços? Porque derrete com carinho.",
    "O que o tomate disse para a cebola? Não me faça chorar!",
    "Por que a lua nunca se perde? Porque tem o sol como guia.",
    "O que a árvore disse para a serra? Por favor, não me corte.",
    "Por que o sorvete se esconde? Porque tem medo do calor.",
    "O que o vento disse para a folha? Vamos dançar juntos.",
    "Por que a bola não fala? Porque só sabe rolar.",
    "Por que o pão dorme cedo? Porque está esgotado.",
    "O que a impressora disse para o cartucho? Sem você, eu não funciono.",
    "Por que o rato não vai à festa? Porque tem medo do gato.",
    "Por que o cavalo não canta? Porque está sem cordas vocais.",
    "O que a escada disse para o degrau? Estamos juntos na subida.",
    "Por que o peixe não gosta de internet? Porque já vive na rede.",
    "O que o chocolate disse para o brigadeiro? Você me deixa mais doce.",
    "Por que o computador adora café? Porque aumenta a energia.",
    "Por que o livro de história está sempre cansado? Porque vive relembrando o passado.",
    "O que a abelha disse para o mel? Sem você, não sou nada.",
    "Por que a galinha entrou no cinema? Para assistir à galinha pintadinha.",
    "O que o lápis disse para o apontador? Para de roer minhas ideias!",
    "Por que o sol nunca se esconde? Porque está sempre brilhando.",
    "Por que o ovo não gosta de brigas? Porque se quebra facilmente.",
    "O que o bolo disse para a cobertura? Você me completa.",
    "Por que a bicicleta gosta de música? Porque pedala no ritmo.",
    "Por que o computador não mente? Porque tem bits de verdade.",
    "O que a lua disse para a estrela? Brilha mais que eu.",
    "Por que o rádio adora notícias? Porque está sempre antenado.",
    "Por que o macaco gosta de bananas? Porque dá energia.",
    "O que a impressora disse para o papel? Você é meu par perfeito.",
    "Por que o cachorro gosta de corrida? Porque adora correr atrás.",
    "Por que o vento é bagunceiro? Porque vive soprando tudo.",
    "Por que o sorvete sorriu? Porque estava no pote da felicidade.",
    "O que o lápis disse para a borracha? Você apaga minhas falhas.",
    "Por que a cadeira gosta de festas? Porque é sempre convidada para sentar.",
    "Por que a galinha atravessou o rio? Para chegar ao outro lado.",
    "O que o pão disse para a manteiga? Você me deixa mais gostoso.",
    "Por que o chocolate adora calor? Porque derrete de alegria.",
    "O que a bicicleta disse para o ciclista? Vamos pedalar juntos.",
    "Por que o computador ama matemática? Porque trabalha com números.",
    "O que o livro disse para o estudante? Abra-me para aprender.",
    "Por que o vento não gosta de segredos? Porque tudo espalha.",
    "Por que o sorvete não fala? Porque é gelado demais.",
    "O que o lápis disse para o caderno? Você completa minha história.",
    "Por que o tomate ficou vermelho? Porque viu o ketchup.",
    "O que a bola disse para o chão? Não me derrube!",
    "Por que o relógio é pontual? Porque não quer perder tempo.",
    "O que o fogo disse para a vela? Não se apague por mim.",
    "Por que o rádio adora música? Porque está sempre na sintonia certa.",
    "Por que o cavalo gosta de trote? Porque é rápido e elegante.",
    "O que o ovo disse para a frigideira? Não me queime!",
    "Por que o pão nunca mente? Porque tem massa de verdade.",
    "Por que o gato não gosta de água? Porque detesta banho molhado.",
    "O que o computador disse para a impressora? Trabalhamos em equipe.",
    "Por que o chocolate adora abraços? Porque se derrete de carinho.",
    "O que o lápis disse para o apontador? Você me deixa afiado.",
    "Por que o vento não descansa? Porque está sempre soprando.",
    "Por que o sorvete gosta do verão? Porque combina com calor.",
    "O que a escada disse para o degrau? Estamos subindo juntos.",
    "Por que o rádio nunca dorme? Porque está sempre ligado.",
    "O que o bolo disse para a cobertura? Você me deixa mais doce.",
    "Por que o pão adora fermento? Porque dá crescimento.",
    "Por que o peixe não gosta de escola? Porque já vive na rede.",
    "O que o sol disse para a lua? Você brilha à noite.",
    "Por que o computador gosta de café? Para manter a energia.",
    "O que o chocolate disse para o brigadeiro? Você me completa.",
    "Por que o livro de história chora? Porque revive o passado.",
    "Por que o tomate foi ao médico? Porque estava vermelho demais.",
    "O que a bicicleta disse para o ciclista? Vamos juntos!",
    "Por que o vento é brincalhão? Porque sempre sopra coisas.",
    "O que o pão disse para a manteiga? Você me derrete.",
    "Por que o gato não fala? Porque mia demais.",
    "Por que o computador não gosta de chuva? Porque detesta curto-circuito.",
    "O que o tomate disse para o pimentão? Vamos juntos para a salada!",
    "Por que o lápis ficou triste? Porque perdeu a ponta no caminho.",
    "O que o pão disse para a frigideira? Não me queime, por favor!",
    "Por que a galinha atravessou o computador? Para chegar ao outro byte.",
    "O que o chocolate disse para o sorvete? Você me deixa derretido.",
    "Por que o gato usa computador? Para caçar o mouse.",
    "O que a cadeira disse para a mesa? Estamos juntos na refeição.",
    "Por que o sol nunca se esconde? Porque gosta de brilhar.",
    "O que o vento disse para a folha? Vamos dançar juntos!",
    "Por que o bolo se escondeu? Porque tinha medo de ser comido.",
    "O que o rádio disse para o CD? Você é vintage, mas legal.",
    "Por que o ovo não fala? Porque quebra com facilidade.",
    "O que o cavalo disse para o boi? Vamos correr juntos!",
    "Por que a escada é paciente? Porque sobe degrau por degrau.",
    "O que o pão disse para a manteiga? Você me deixa mais gostoso.",
    "Por que o sorvete gosta do verão? Porque combina com calor.",
    "O que o lápis disse para o caderno? Você completa minhas ideias.",
    "Por que o computador gosta de matemática? Porque lida com números.",
    "O que a bola disse para o chão? Não me derrube!",
    "Por que o chocolate se esconde? Porque derrete facilmente.",
    "O que o peixe disse para a rede? Não me pegue!",
    "Por que o rádio adora música? Porque está sempre sintonizado.",
    "O que a abelha disse para a flor? Você me deixa meloso.",
    "Por que o vento gosta de brincar? Porque adora soprar.",
    "O que o relógio disse para o calendário? Estamos sincronizados.",
    "Por que o pão dorme cedo? Porque está esgotado.",
    "O que o livro disse para o estudante? Abra-me para aprender.",
    "Por que a bicicleta não mente? Porque sempre pedala com verdade.",
    "O que o sol disse para a lua? Você brilha melhor à noite.",
    "Por que o gato não gosta de água? Porque detesta banho.",
    "O que o computador disse para a impressora? Trabalhamos juntos.",
    "Por que o ovo foi ao médico? Porque estava se sentindo fraco.",
    "O que a escada disse para o degrau? Subimos juntos.",
    "Por que o chocolate adora abraços? Porque derrete de carinho.",
    "O que o lápis disse para o apontador? Você me deixa afiado.",
    "Por que o vento nunca descansa? Porque está sempre soprando.",
    "O que o bolo disse para a cobertura? Você me deixa doce.",
    "Por que o pão gosta de fermento? Porque dá crescimento.",
    "Por que o peixe não gosta de escola? Porque já vive na rede.",
    "Por que o tomate foi ao médico? Porque estava vermelho demais.",
    "O que a bicicleta disse para o ciclista? Vamos juntos!",
    "Por que o vento é brincalhão? Porque sempre sopra coisas.",
    "O que o pão disse para a manteiga? Você me derrete.",
    "Por que o gato não fala? Porque mia demais.",
    "O que o sorvete disse para a casquinha? Você me segura!",
    "Por que a lua adora a noite? Porque brilha sem parar.",
    "O que o computador disse para o mouse? Vamos clicar juntos.",
    "Por que o chocolate adora festa? Porque gosta de se derreter.",
    "O que o rádio disse para a antena? Estamos sintonizados.",
    "Por que o lápis nunca se perde? Porque sempre deixa um traço.",
    "O que o fogo disse para a vela? Não se apague por mim.",
    "Por que o macaco não gosta de matemática? Porque faz contas de cabeça.",
    "O que a impressora disse para o papel? Você é meu par perfeito.",
    "Por que o cachorro gosta de corrida? Porque adora correr atrás.",
    "O que o vento disse para o cabelo? Me deixa bagunçado.",
    "Por que a bola não corre? Porque só sabe rolar.",
    "O que o queijo disse para o pão? Você me completa.",
    "Por que a porta não gosta de festa? Porque sempre fica de fora.",
    "Por que o milho virou pipoca? Porque explodiu de alegria.",
    "Por que a água não gosta de segredo? Porque escorre tudo.",
    "O que o jacaré disse para o amigo? Croc, croc, estou aqui!",
    "Por que o boi se esconde? Porque é manso demais.",
    "Por que a galinha canta de manhã? Para acordar o vizinho.",
    "O que a lua disse para o sol? Você me ofusca.",
    "Por que o poste é bom conselheiro? Porque ilumina os caminhos.",
    "Por que o ovo não conta piadas? Porque quebra a casca de rir.",
    "Por que o caminhão é forte? Porque carrega o mundo.",
    "O que a lâmpada disse ao interruptor? Acenda-me por favor.",
    "Por que o pombo não usa WhatsApp? Porque já tem pombo correio.",
    "Qual é o cúmulo do frio? Tomar banho de neve sem se molhar.",
    "Por que o sorvete não fala nada? Porque está gelado demais.",
    "O que o pneu disse para o carro? Estou ligado em você.",
    "Por que a banana é engraçada? Porque dá muita risada-fruta.",
    "Por que o celular não briga? Porque prefere ficar no modo silencioso.",
    "O que o boi falou para a vaca? Te amoOOooo!",
    "Por que o computador foi preso? Porque bateu no mouse.",
    "Por que o lápis nunca se perde? Porque sempre deixa um traço.",
    "O que o fogo disse para a vela? Não derreta por mim.",
    "Por que o macaco não gosta de matemática? Porque vive fazendo contas de cabeça.",
    "Por que o sorvete foi ao psicólogo? Porque estava derretendo de preocupação.",
    "O que o lápis disse para o caderno? Sem você, minhas ideias não têm forma.",
    "Por que o pão foi ao médico? Porque se sentia amassado.",
    "O que o tomate disse para o outro tomate? Ketchup comigo!",
    "Por que o gato não gosta de água? Porque detesta banho molhado.",
    "O que a cadeira disse para a mesa? Estamos juntos nas refeições.",
    "Por que o sol não precisa de relógio? Porque sempre brilha na hora certa.",
    "O que o vento disse para a folha? Vamos dançar juntos!",
    "Por que o bolo se escondeu? Porque tinha medo de ser comido.",
    "O que o rádio disse para o CD? Você ainda é clássico.",
    "Por que o ovo não fala? Porque não quer quebrar.",
    "O que o cavalo disse para o boi? Vamos correr juntos!",
    "Por que a escada é paciente? Porque sobe degrau por degrau.",
    "O que o pão disse para a manteiga? Você me deixa delicioso.",
    "Por que o sorvete ama o verão? Porque combina com calor.",
    "O que o lápis disse para o caderno? Você completa minhas ideias.",
    "Por que o computador ama matemática? Porque lida com números.",
    "O que a bola disse para o chão? Não me derrube!",
    "Por que o chocolate se esconde? Porque derrete facilmente.",
    "O que o peixe disse para a rede? Não me pegue!",
    "Por que o rádio adora música? Porque está sempre sintonizado.",
    "O que a abelha disse para a flor? Você me deixa meloso.",
    "Por que o vento gosta de brincar? Porque adora soprar.",
    "O que o relógio disse para o calendário? Estamos sincronizados.",
    "Por que o pão dorme cedo? Porque precisa descansar.",
    "O que o livro disse para o estudante? Abra-me e aprenda.",
    "Por que a bicicleta não mente? Porque sempre pedala com verdade.",
    "O que o sol disse para a lua? Você brilha melhor à noite.",
    "Por que o gato não gosta de banho? Porque é molhado demais.",
    "O que o computador disse para a impressora? Trabalhamos juntos.",
    "Por que o ovo foi ao médico? Porque estava fraco.",
    "O que a escada disse para o degrau? Subimos juntos.",
    "Por que o chocolate adora abraços? Porque derrete de carinho.",
    "O que o lápis disse para o apontador? Você me deixa afiado.",
    "Por que o vento nunca descansa? Porque está sempre soprando.",
    "O que o bolo disse para a cobertura? Você me deixa doce.",
    "Por que o pão gosta de fermento? Porque cresce com ele.",
    "Por que o peixe não gosta de escola? Porque já vive na rede.",
    "Por que o tomate foi ao médico? Porque estava vermelho demais.",
    "O que a bicicleta disse para o ciclista? Vamos juntos!",
    "Por que o vento é brincalhão? Porque sempre sopra coisas.",
    "O que o pão disse para a manteiga? Você me derrete.",
    "Por que o gato não fala? Porque mia demais.",
    "O que o sorvete disse para a casquinha? Você me segura!",
    "Por que a lua adora a noite? Porque brilha sem parar.",
    "O que o computador disse para o mouse? Vamos clicar juntos.",
    "Por que o chocolate adora festa? Porque gosta de se derreter.",
    "O que o rádio disse para a antena? Estamos sintonizados.",
    "Por que o lápis nunca se perde? Porque sempre deixa um traço.",
    "O que o fogo disse para a vela? Não se apague por mim.",
    "Por que o macaco não gosta de matemática? Porque faz contas de cabeça.",
    "O que a impressora disse para o papel? Você é meu par perfeito.",
    "Por que o cachorro gosta de corrida? Porque adora correr atrás.",
    "O que o vento disse para o cabelo? Me deixa bagunçado.",
    "Por que a bola não corre? Porque só sabe rolar.",
    "O que o queijo disse para o pão? Você me completa.",
    "Por que a porta não gosta de festa? Porque sempre fica de fora.",
    "Por que o milho virou pipoca? Porque explodiu de alegria.",
    "Por que a água não gosta de segredo? Porque escorre tudo.",
    "O que o jacaré disse para o amigo? Croc, croc, estou aqui!",
    "Por que o boi se esconde? Porque é manso demais.",
    "Por que a galinha canta de manhã? Para acordar o vizinho.",
    "O que a lua disse para o sol? Você me ofusca.",
    "Por que o poste é bom conselheiro? Porque ilumina os caminhos.",
    "Por que o ovo não conta piadas? Porque quebra a casca de rir.",
    "Por que o caminhão é forte? Porque carrega o mundo.",
    "O que a lâmpada disse ao interruptor? Acenda-me por favor.",
    "Por que o pombo não usa WhatsApp? Porque já tem pombo correio.",
    "Qual é o cúmulo do frio? Tomar banho de neve sem se molhar.",
    "Por que o sorvete não fala nada? Porque está gelado demais.",
    "O que o pneu disse para o carro? Estou ligado em você.",
    "Por que a banana é engraçada? Porque dá muita risada-fruta.",
    "Por que o celular não briga? Porque prefere ficar no modo silencioso.",
    "O que o boi falou para a vaca? Te amoOOooo!",
    "Por que o computador foi preso? Porque bateu no mouse.",
    "Por que o lápis nunca se perde? Porque sempre deixa um traço.",
    "O que o fogo disse para a vela? Não derreta por mim.",
    "Por que o macaco não gosta de matemática? Porque vive fazendo contas de cabeça.",
    "O que a impressora disse para o papel? Você é meu par perfeito.",
    "Por que o gato adora caixas? Porque gosta de se esconder.",
    "O que o pão disse para a geléia? Você me deixa mais doce.",
    "Por que o sorvete gosta do verão? Porque combina com calor.",
    "O que o lápis disse para a borracha? Você apaga minhas falhas.",
    "Por que a bicicleta não gosta de montanhas? Porque prefere o plano.",
    "O que o chocolate disse para o brigadeiro? Você me completa.",
    "Por que o tomate não se perde? Porque sempre segue o ketchup.",
    "O que o vento disse para a nuvem? Não me leve a mal.",
    "Por que o bolo não se irrita? Porque mantém a calma.",
    "O que a galinha disse para o ovo? Vamos juntos!",
    "Por que o computador gosta de café? Porque aumenta a energia.",
    "O que a escada disse para o corrimão? Estou contigo.",
    "Por que o sol nunca se esconde? Porque gosta de brilhar.",
    "O que o rádio disse para a estação? Estou contigo.",
    "Por que o lápis ama o papel? Porque sem ele não escreve nada.",
    "O que a abelha disse para a flor? Você me deixa meloso.",
    "Por que o pão não briga? Porque é massa pacífica.",
    "O que o queijo disse para o pão? Você me completa.",
    "Por que o milho explode? Porque virou pipoca de alegria.",
    "O que o vento disse para o cabelo? Me bagunce sem medo!",
    "Por que o computador foi ao médico? Porque estava com vírus!",
    "O que a lâmpada disse para o interruptor? Você me acende!",
    "Por que a geladeira não fala? Porque está cheia de coisas.",
    "O que o pão disse para o forno? Me aqueça devagar.",
    "Por que o livro de matemática se sentiu mal? Porque tinha muitos problemas.",
    "O que o peixe disse para o aquário? Estou me sentindo preso!",
    "Por que o macaco não joga cartas? Porque tem medo do baralho.",
    "O que a cadeira disse para o tapete? Você me deixa confortável.",
    "Por que a lua está sempre calma? Porque não tem gravidade.",
    "O que o sorvete disse para a colher? Você me deixa feliz!",
    "Por que o lápis se divorciou da borracha? Porque ele estava sem ponta.",
    "O que o rádio disse para a bateria? Vamos juntos na frequência!",
    "Por que a caneta adora escrever? Porque gosta de deixar rastro.",
    "O que o bolo disse para a frigideira? Não me queime!",
    "Por que o tomate se escondeu na salada? Porque ficou tímido.",
    "O que o cavalo disse para o coelho? Vamos galopar!",
    "Por que o chocolate não gosta de sol? Porque derrete rápido.",
    "O que o vento disse para a cortina? Mexa-se comigo!",
    "Por que a escada não mente? Porque sempre está na vertical.",
    "O que o pão disse para o café? Você me completa.",
    "Por que a bicicleta não fala? Porque só pedala.",
    "O que o queijo disse para a goiabada? Você é meu doce favorito.",
    "Por que o peixe não gosta de festa? Porque não gosta de agitação.",
    "O que o sol disse para a estrela? Você brilha no seu momento.",
    "Por que o ovo não gosta de piadas? Porque se quebra de rir.",
    "O que a abelha disse para a flor? Você me deixa doce.",
    "Por que o cachorro não gosta de chuva? Porque se molha demais.",
    "O que o chocolate disse para o brigadeiro? Você me deixa feliz!",
    "Por que a porta não se cansa? Porque abre e fecha sem parar.",
    "O que o lápis disse para o caderno? Você guarda meus segredos.",
    "Por que a lua não toma banho? Porque não gosta de água!",
    "O que o computador disse para a tela? Você me mostra o caminho.",
    "Por que o pão dorme cedo? Porque precisa descansar.",
    "O que a bola disse para o chão? Não me derrube!",
    "Por que o vento gosta de brincar? Porque está sempre soprando.",
    "O que o bolo disse para a cobertura? Você me deixa doce!",
    "Por que o tomate não fala? Porque se sente vermelho.",
    "O que o relógio disse para o calendário? Estamos no mesmo tempo.",
    "Por que o chocolate adora frio? Porque não derrete rápido.",
    "O que o sorvete disse para a casquinha? Você me segura firme!",
    "Por que o gato não usa computador? Porque tem medo do mouse.",
    "O que o pão disse para a manteiga? Você me deixa saboroso.",
    "Por que o cavalo gosta de trote? Porque adora correr.",
    "O que o lápis disse para a borracha? Você me deixa limpo.",
    "Por que a bicicleta não mente? Porque sempre pedala na verdade.",
    "O que o computador disse para o mouse? Vamos trabalhar juntos.",
    "Por que o ovo foi ao médico? Porque se sentia quebrado.",
    "O que o bolo disse para a frigideira? Não me queime!",
    "Por que o rádio adora música? Porque está sempre sintonizado.",
    "O que a cadeira disse para a mesa? Você me apoia.",
    "Por que o sorvete gosta do verão? Porque combina com calor.",
    "O que o sol disse para a lua? Você brilha à noite.",
    "Por que o macaco não gosta de matemática? Porque prefere bananas.",
    "O que o chocolate disse para o brigadeiro? Você me completa.",
    "Por que o pão gosta de fermento? Porque cresce com ele.",
    "O que o peixe disse para a rede? Não me prenda!",
    "Por que a lua está sempre calma? Porque não tem gravidade.",
    "O que a escada disse para o degrau? Subimos juntos.",
    "Por que o tomate se escondeu? Porque ficou vermelho.",
    "O que o vento disse para a folha? Vamos dançar!",
    "Por que o ovo não fala? Porque se quebra fácil.",
    "O que o bolo disse para a cobertura? Você me deixa doce.",
    "Por que o chocolate se escondeu? Porque derrete facilmente.",
    "O que o lápis disse para o apontador? Você me deixa afiado.",
    "Por que o rádio adora música? Porque está sempre ligado.",
    "O que a bicicleta disse para o ciclista? Vamos juntos!",
    "Por que o gato não gosta de banho? Porque se molha demais.",
    "O que o pão disse para a geléia? Você me deixa mais doce.",
    "O que o fogo disse para a vela? Não se apague por mim.",
    "Por que o sorvete não fala nada? Porque está gelado demais.",
    "O que o pneu disse para o carro? Estou ligado em você.",
    "Por que o milho virou pipoca? Porque explodiu de alegria.",
    "Por que a água não gosta de segredo? Porque escorre tudo.",
    "O que o jacaré disse para o amigo? Croc, croc, estou aqui!",
    "Por que a galinha canta de manhã? Para acordar o vizinho.",
    "O que a lua disse para o sol? Você me ofusca.",
    "Por que o poste é bom conselheiro? Porque ilumina os caminhos.",
    "Por que o ovo não conta piadas? Porque quebra a casca de rir.",
    "O que a lâmpada disse ao interruptor? Acenda-me por favor.",
    "Por que o pombo não usa WhatsApp? Porque já tem pombo correio.",
    "Qual é o cúmulo do frio? Tomar banho de neve sem se molhar.",
    "Por que o celular não briga? Porque prefere ficar no modo silencioso.",
    "O que o boi falou para a vaca? Te amoOOooo!",
    "Por que o milho explode? Porque virou pipoca de alegria.",
    "O que o vento disse para o cabelo? Me bagunce sem medo!",
    "Por que a geladeira é silenciosa? Porque não gosta de fofocas.",
    "O que o pão disse para o forno? Me aqueça devagar.",
    "Por que a banana é engraçada? Porque dá risada-fruta.",
    "O que o peixe disse para o aquário? Estou me sentindo preso!",
    "Por que a bicicleta não gosta de montanhas? Porque prefere o plano.",
    "O que o chocolate disse para a goiabada? Você me completa.",
    "O que o sorvete disse para a colher? Você me faz feliz!",
    "Por que o lápis se divorciou da borracha? Porque ele estava sem ponta.",
    "O que o livro disse para o estudante? Abra-me e aprenda!",
    "Por que o cachorro não gosta de chuva? Porque se molha demais.",
    "O que o bolo disse para a frigideira? Não me queime!",
    "Por que o vento adora brincar? Porque está sempre soprando.",
    "O que o sol disse para a lua? Brilha no seu momento!",
    "Por que a escada não mente? Porque está sempre na vertical.",
    "O que o queijo disse para o pão? Você me completa.",
    "Por que o computador levou óculos? Porque tinha problemas de visão!",
    "O que o pão falou para a torrada? Você me deixa crocante!",
    "Por que a galinha atravessou o teclado? Para clicar na outra tecla!",
    "O que o tomate disse para o pepino? Você me deixa verde de inveja!",
    "Por que o lápis não briga? Porque prefere ficar afiado.",
    "O que o sorvete disse para o sol? Não me derreta!",
    "Por que o gato não gosta de chuva? Porque fica todo molhado.",
    "O que a lâmpada disse para o interruptor? Acenda-me por favor!",
    "Por que o bolo não se irrita? Porque mantém a calma.",
    "O que o rádio disse para a antena? Estamos sempre conectados!",
    "Por que o ovo não conta piadas? Porque se quebra de rir.",
    "O que o vento disse para a cortina? Mexa-se comigo!",
    "Por que a bicicleta não fala? Porque só pedala.",
    "O que o chocolate disse para a bala? Você me deixa feliz!",
    "Por que o sol nunca se esconde? Porque gosta de brilhar.",
    "O que o lápis disse para o caderno? Você guarda meus segredos.",
    "Por que o computador gosta de café? Para ganhar energia.",
    "O que o fogo disse para a vela? Não se apague por mim.",
    "Por que o milho virou pipoca? Porque explodiu de alegria.",
    "O que o pneu disse para o carro? Estou ligado em você.",
    "Por que o programador foi ao médico? Porque ele estava com um loop infinito de dor e não conseguia dar break."
    "Porque o livro terminou o relacionamento? Porque ele se chamava Carrascosa."
]